const US_STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
  'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois',
  'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
  'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
  'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
  'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
  'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
  'West Virginia', 'Wisconsin', 'Wyoming',
];

export const COUNTRIES = [
  { name: 'United States', states: US_STATES, timezones: ['Eastern Time (GMT-5)', 'Central Time (GMT-6)', 'Mountain Time (GMT-7)', 'Pacific Time (GMT-8)', 'Alaska Time (GMT-9)', 'Hawaii Time (GMT-10)'] },
  { name: 'Canada', timezones: ['Newfoundland Time (GMT-3:30)', 'Atlantic Time (GMT-4)', 'Eastern Time (GMT-5)', 'Central Time (GMT-6)', 'Mountain Time (GMT-7)', 'Pacific Time (GMT-8)'] },
  { name: 'Australia', timezones: ['Western Australia (GMT+8)', 'Central Australia (GMT+9:30)', 'Eastern Australia (GMT+10)'] },
  { name: 'Russia', timezones: ['Kaliningrad Time (GMT+2)', 'Moscow Time (GMT+3)', 'Yekaterinburg Time (GMT+5)', 'Novosibirsk Time (GMT+7)', 'Vladivostok Time (GMT+10)'] },
  { name: 'Brazil', timezones: ['Acre Time (GMT-5)', 'Amazon Time (GMT-4)', 'Brasília Time (GMT-3)', 'Fernando de Noronha Time (GMT-2)'] },
  { name: 'Mexico', timezones: ['Northwest Zone (GMT-8)', 'Pacific Zone (GMT-7)', 'Central Zone (GMT-6)', 'Southeast Zone (GMT-5)'] },

  { name: 'United Kingdom', timezones: ['Greenwich Mean Time (GMT+0)'] },
  { name: 'Ireland', timezones: ['Greenwich Mean Time (GMT+0)'] },
  { name: 'Portugal', timezones: ['Western European Time (GMT+0)'] },
  { name: 'Iceland', timezones: ['Greenwich Mean Time (GMT+0)'] },
  { name: 'Germany', timezones: ['Central European Time (GMT+1)'] },
  { name: 'France', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Spain', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Italy', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Netherlands', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Belgium', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Switzerland', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Austria', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Poland', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Sweden', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Norway', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Denmark', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Czech Republic', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Hungary', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Croatia', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Slovakia', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Slovenia', timezones: ['Central European Time (GMT+1)'] },
  { name: 'Finland', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Greece', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Romania', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Bulgaria', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Estonia', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Latvia', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Lithuania', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Ukraine', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Israel', timezones: ['Israel Standard Time (GMT+2)'] },
  { name: 'South Africa', timezones: ['South Africa Standard Time (GMT+2)'] },
  { name: 'Egypt', timezones: ['Eastern European Time (GMT+2)'] },
  { name: 'Turkey', timezones: ['Turkey Time (GMT+3)'] },
  { name: 'Saudi Arabia', timezones: ['Arabia Standard Time (GMT+3)'] },
  { name: 'United Arab Emirates', timezones: ['Gulf Standard Time (GMT+4)'] },
  { name: 'Pakistan', timezones: ['Pakistan Standard Time (GMT+5)'] },
  { name: 'India', timezones: ['India Standard Time (GMT+5:30)'] },
  { name: 'Sri Lanka', timezones: ['India Standard Time (GMT+5:30)'] },
  { name: 'Nepal', timezones: ['Nepal Time (GMT+5:45)'] },
  { name: 'Bangladesh', timezones: ['Bangladesh Standard Time (GMT+6)'] },
  { name: 'Thailand', timezones: ['Indochina Time (GMT+7)'] },
  { name: 'Vietnam', timezones: ['Indochina Time (GMT+7)'] },
  { name: 'Indonesia', timezones: ['Western Indonesia Time (GMT+7)'] },
  { name: 'Singapore', timezones: ['Singapore Standard Time (GMT+8)'] },
  { name: 'Malaysia', timezones: ['Malaysia Time (GMT+8)'] },
  { name: 'Philippines', timezones: ['Philippine Standard Time (GMT+8)'] },
  { name: 'China', timezones: ['China Standard Time (GMT+8)'] },
  { name: 'South Korea', timezones: ['Korea Standard Time (GMT+9)'] },
  { name: 'Japan', timezones: ['Japan Standard Time (GMT+9)'] },
  { name: 'New Zealand', timezones: ['New Zealand Time (GMT+12)'] },

  { name: 'Argentina', timezones: ['Argentina Time (GMT-3)'] },
  { name: 'Chile', timezones: ['Chile Time (GMT-4)'] },
  { name: 'Colombia', timezones: ['Colombia Time (GMT-5)'] },
  { name: 'Peru', timezones: ['Peru Time (GMT-5)'] },
  { name: 'Ecuador', timezones: ['Ecuador Time (GMT-5)'] },
  { name: 'Venezuela', timezones: ['Venezuela Time (GMT-4)'] },
  { name: 'Uruguay', timezones: ['Uruguay Time (GMT-3)'] },
  { name: 'Paraguay', timezones: ['Paraguay Time (GMT-4)'] },
  { name: 'Bolivia', timezones: ['Bolivia Time (GMT-4)'] },

  { name: 'Nigeria', timezones: ['West Africa Time (GMT+1)'] },
  { name: 'Kenya', timezones: ['East Africa Time (GMT+3)'] },
  { name: 'Morocco', timezones: ['Western European Time (GMT+0)'] },
];

export function getCountry(name) {
  return COUNTRIES.find((c) => c.name === name) || null;
}
